### PR TITLE
Add a note on when collation order is needed

### PR DESCRIPTION
**Pull request by IndrajeetPatil**

### CODE REVIEW

**Comment by IndrajeetPatil** [comment]
*bump*

**Comment by IndrajeetPatil** [comment]
@wch Lemme know if it makes sense to include this content in this vignette.

**Comment by wch** [comment]
Hi, sorry for being slow to get back to you. I don't think it's really necessary to add this, since it's an issue with packages in general, not just R6, and the R6 code in the example may actually distract the reader from the actual issue, which is that you're trying to use something before it has been created. Also, the Introduction vignette is already a bit overstuffed, so I'd prefer not to add more to it in this case.

**Comment by IndrajeetPatil** [comment]
> Also, the Introduction vignette is already a bit overstuffed, so I'd prefer not to add more to it in this case.

I fully agree.

I wonder if we should have a new vignette for all sections that are currently under "Other Topics". Maybe named something like "advanced usage"?

Screenshot 2022-06-22 at 12 18 23

**Pull request closed without merging**
